version: "3.7"

services:
  frontend:
    image: docker.pkg.github.com/kcrebound/smena-hackathon/hfrontend:0.1
    deploy:
      replicas: 8
      labels:
        - "traefik.enable=true"
        # redirect to https
        - "traefik.http.routers.frontend-http.rule=Host(`farfor.tech`)"
        - "traefik.http.routers.frontend-http.entrypoints=web"
        - "traefik.http.routers.frontend-http.middlewares=redirect-to-https"
        # middleware redirect
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

        # https
        - "traefik.http.routers.frontend.rule=Host(`farfor.tech`)"
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
        - "traefik.http.services.frontend-service.loadbalancer.server.port=3000"
      placement:
        constraints:
          - node.role == worker
    networks:
      - traefik-public

  backend:
    image: docker.pkg.github.com/kcrebound/smena-hackathon/hbackend:0.1
    deploy:
      replicas: 20
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        # redirect to https
        - "traefik.http.routers.backend-http.rule=Host(`api.farfor.tech`)"
        - "traefik.http.routers.backend-http.entrypoints=web"
        - "traefik.http.routers.backend-http.middlewares=redirect-to-https"
        # middleware redirect
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

        # https
        - "traefik.http.routers.backend.rule=Host(`api.farfor.tech`)"
        - "traefik.http.services.backend-service.loadbalancer.server.port=8000"
        - "traefik.http.routers.backend.entrypoints=websecure"
        - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
    networks:
      - traefik-public

  traefik:
    image: traefik:v2.0.4
    command:
      - "--api.insecure=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-public"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=testmail@farfor.tech"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    networks:
      - traefik-public
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  traefik-public:
    external: true